name: buildPackage

description: Build library code and run tests

inputs:
  libraryPath:
    description: 'The path to the library .csproj file'
    required: true
  testsPath:
    description: 'The path to the unit tests .csproj file guarding the library'
    required: false
  testsResultsPath:
    description: 'The path to the unit tests results folder'
    required: false

runs:
  using: "composite"
  # Defining the action steps
  steps:
    - name: Use .NET Core sdk 7.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x
        
    - name: 'Build project'
      run: dotnet build ${{ inputs.libraryPath }} --configuration Release
      shell: bash

    - name: Run unit tests
      if: "${{ inputs.testsPath != '' }}"
      run: dotnet test ${{ inputs.testsPath }} --configuration release --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura
      continue-on-error: false
      shell: bash

    - name: Publish Code Coverage Report
      if: "${{ inputs.testsPath != '' }}"
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage
        path: ${{ inputs.testsResultsPath }}/*/coverage.cobertura.xml