<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>12</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\CodeCreate.Core\CodeCreate.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="EasyNetQ" Version="7.8.0" />
      <PackageReference Include="EasyNetQ.Serialization.NewtonsoftJson" Version="7.8.0" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="6.0.0" />
    </ItemGroup>

</Project>
