jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    needs: ${{ inputs.buildJobName }}
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download nuget package artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: ${{ inputs.artifactName }}

      - name: Prep package
        run: dotnet nuget add source --username ${{ inputs.username }} --password ${{ inputs.password }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/codecreate-sa/index.json"

      - name: Push package to GitHub packages
        if: needs.${{ inputs.buildJobName }}.outputs.CommitsSinceVersionSource > 0 # Only release if there has been a commit/version change  
        run: dotnet nuget push ${{ inputs.artifactName }}/*.nupkg --api-key ${{ inputs.password }} --source "github"

      - name: Create Release
        if: needs.${{ inputs.buildJobName }}.outputs.CommitsSinceVersionSource > 0 # Only release if there has been a commit/version change  
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.${{ inputs.buildJobName }}.outputs.Version }}
          name: Release ${{ needs.${{ inputs.buildJobName }}.outputs.Version }}
          artifacts: "${{ inputs.artifactName }}/*"
          token: ${{ inputs.password }}