name: releasePackage

description: Add the GitHub Packages nuget source and publish the package 

inputs:
  username:
    description: 'The username to be used to connect to GitHub Packages nuget source'
    required: true
  password:
    description: 'The api key to be used to connect to GitHub Packages nuget source'
    required: true
  artifactName:
    description: 'The build artifact name'
    required: true

runs:
  using: "composite"
  # Defining the action steps
  steps:
    - name: Download nuget package artifact
      uses: actions/download-artifact@v1.0.0
      with:
        name: ${{ inputs.artifactName }}
        
    - name: Prep package
      run: dotnet nuget add source --username ${{ inputs.username }} --password ${{ inputs.password }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/codecreate-sa/index.json"
      shell: bash

    - name: Push package to GitHub packages
      run: dotnet nuget push ${{ inputs.artifactName }}/*.nupkg --api-key ${{ inputs.password }} --source "github"
      shell: bash