name: codecreate-core-ci

on:
  pull_request:
    branches:
      - main
    paths:
      - 'lib/CodeCreate.Core/**'
      - 'tests/CodeCreate.Core.Tests.Unit/**'

env:
  LIBRARY_PATH: 'lib/CodeCreate.Core/CodeCreate.Core.csproj'
  TESTS_PATH: 'tests/CodeCreate.Core.Tests.Unit/CodeCreate.Core.Tests.Unit.csproj'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest 
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
        
    - name: Use .NET Core sdk 7.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x

    - name: 'Build project'
      run: dotnet build ${{ env.LIBRARY_PATH }} --configuration Release

    - name: Run Unit Tests
      run: dotnet test ${{ env.TESTS_PATH }} --configuration release --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura
      continue-on-error: true

    - name: Publish Code Coverage Report
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage
        path: tests/CodeCreate.Core.Tests.Unit/TestResults/*/coverage.cobertura.xml