name: codecreate-logging-ci

on:
  pull_request:
    branches:
      - main
    paths:
      - 'lib/CodeCreate.Logging/**'
      - 'tests/CodeCreate.Logging.Tests.Unit/**'

env:
  LIBRARY_PATH: 'lib/CodeCreate.Logging/CodeCreate.Logging.csproj'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest 
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
        
    - name: buildPackage
      id: buildPackage
      uses: "./.github/workflows/templates/buildPackage" # Just need to pass the path from action
      # Defining the variables required in our action
      with:
        libraryPath: ${{ env.LIBRARY_PATH }}