name: codecreate-core-cd

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'lib/CodeCreate.Core/**'
      - 'tests/CodeCreate.Core.Tests.Unit/**'

env:
  DLL_PATH: 'lib/CodeCreate.Core/bin/Release'
  LIBRARY_PATH: 'lib/CodeCreate.Core/CodeCreate.Core.csproj'
  TESTS_PATH: 'tests/CodeCreate.Core.Tests.Unit/CodeCreate.Core.Tests.Unit.csproj'
  TESTS_RESULTS_PATH: 'tests/CodeCreate.Core.Tests.Unit/TestResults'
  ARTIFACT_NAME: 'codeCreatePackage'
  CODECREATE_GH_PACKAGE_SOURCE_USERNAME: ${{ secrets.CODECREATE_GH_PACKAGE_SOURCE_USERNAME }}
  CODECREATE_GH_PACKAGE_SOURCE_PASSWORD: ${{ secrets.CODECREATE_GH_PACKAGE_SOURCE_PASSWORD }}

jobs:
  # Use the "build" job template file with custom inputs
  build:
    name: build
    uses: ./build-job-template.yml
    with:
      dllPath: ${{ env.DLL_PATH }}
      libraryPath: ${{ env.LIBRARY_PATH }}
      testsPath: ${{ env.TESTS_PATH }}
      testsResultsPath: ${{ env.TESTS_RESULTS_PATH }}
      artifactName: ${{ env.ARTIFACT_NAME }}
        
  # Use the "release" job template file with custom inputs
  release:
    name: Release
    uses: ./release-job-template.yml
    with:
      buildJobName: build
      artifactName: ${{ env.ARTIFACT_NAME }}
      username: ${{ env.CODECREATE_GH_PACKAGE_SOURCE_USERNAME }}
      password: ${{ env.CODECREATE_GH_PACKAGE_SOURCE_PASSWORD }}